begin;

create table if not exists public.mastery_exercise_links (
  id uuid primary key default gen_random_uuid(),
  mastery_id uuid not null references public.masteries(id) on delete cascade,
  exercise_key text not null,
  exercise_name text not null,
  exercise_id uuid null,
  source_type text not null
    check (source_type in ('exercise_library', 'training_block', 'alias')),
  created_at timestamptz not null default now(),
  unique (source_type, exercise_name)
);

create index if not exists mastery_exercise_links_mastery_idx
  on public.mastery_exercise_links (mastery_id, source_type);

create index if not exists mastery_exercise_links_key_idx
  on public.mastery_exercise_links (source_type, exercise_key);

alter table if exists public.mastery_exercise_links enable row level security;

drop policy if exists "Authenticated users can read mastery exercise links" on public.mastery_exercise_links;
create policy "Authenticated users can read mastery exercise links"
  on public.mastery_exercise_links for select
  to authenticated
  using (true);

grant select on public.mastery_exercise_links to authenticated;

with
category_seed(slug, name, sort_order) as (
  values
    ('fitness', 'Fitness', 1),
    ('musculation', 'Musculation', 2),
    ('course-a-pied', 'Course à pied', 3),
    ('trail', 'Trail', 4),
    ('marche', 'Marche', 5),
    ('velo', 'Vélo', 6),
    ('vtt', 'VTT', 7),
    ('natation', 'Natation', 8),
    ('cardio-indoor', 'Cardio indoor', 9),
    ('mobilite-souplesse', 'Mobilité & souplesse', 10),
    ('ski-alpin', 'Ski alpin', 11),
    ('ski-randonnee', 'Ski de randonnée', 12),
    ('ski-de-fond', 'Ski de fond', 13),
    ('raquettes', 'Raquettes', 14),
    ('escalade', 'Escalade', 15),
    ('via-ferrata', 'Via ferrata', 16),
    ('alpinisme', 'Alpinisme', 17),
    ('course-orientation', 'Course d’orientation', 18),
    ('gravel', 'Gravel', 19),
    ('home-trainer', 'Home trainer / vélo indoor', 20),
    ('football', 'Football', 21),
    ('rugby', 'Rugby', 22),
    ('basketball', 'Basketball', 23),
    ('handball', 'Handball', 24),
    ('volleyball', 'Volleyball', 25),
    ('tennis', 'Tennis', 26),
    ('padel', 'Padel', 27),
    ('badminton', 'Badminton', 28),
    ('tennis-de-table', 'Tennis de table', 29),
    ('boxe', 'Boxe', 30),
    ('sports-de-combat', 'Sports de combat', 31),
    ('danse', 'Danse', 32),
    ('kayak-canoe', 'Kayak / Canoë', 33),
    ('aviron', 'Aviron', 34),
    ('paddle', 'Paddle', 35),
    ('surf', 'Surf', 36),
    ('roller-patinage', 'Roller / Patinage', 37),
    ('triathlon', 'Triathlon', 38),
    ('hyrox-cross-training', 'HYROX / Cross-training', 39)
),
upsert_categories as (
  insert into public.mastery_categories (slug, name, sort_order, active)
  select slug, name, sort_order, true
  from category_seed
  on conflict (slug) do update
  set
    name = excluded.name,
    sort_order = excluded.sort_order,
    active = true
  returning id, slug
),
mastery_seed(slug, name, category_slug, measurement_type, unit, level_family, sort_order) as (
  values
    ('pompes', 'Pompes', 'fitness', 'reps', 'repetitions', 'reps-easy', 1),
    ('pompes-adaptees', 'Pompes adaptées', 'fitness', 'reps', 'repetitions', 'reps-easy', 2),
    ('pompes-inclinees', 'Pompes inclinées', 'fitness', 'reps', 'repetitions', 'reps-easy', 3),
    ('pompes-diamant', 'Pompes diamant', 'fitness', 'reps', 'repetitions', 'reps-medium', 4),
    ('squats-poids-du-corps', 'Squats poids du corps', 'fitness', 'reps', 'repetitions', 'reps-easy', 5),
    ('squats-sautes', 'Squats sautés', 'fitness', 'reps', 'repetitions', 'reps-power', 6),
    ('fentes-alternees', 'Fentes alternées', 'fitness', 'reps', 'repetitions', 'reps-medium', 7),
    ('fentes-arriere', 'Fentes arrière', 'fitness', 'reps', 'repetitions', 'reps-medium', 8),
    ('burpees', 'Burpees', 'fitness', 'reps', 'repetitions', 'reps-burpees', 9),
    ('burpees-adaptes', 'Burpees adaptés', 'fitness', 'reps', 'repetitions', 'reps-medium', 10),
    ('mountain-climbers', 'Mountain climbers', 'fitness', 'duration', 'secondes', 'duration-short', 11),
    ('mountain-climbers-controles', 'Mountain climbers contrôlés', 'fitness', 'duration', 'secondes', 'duration-short', 12),
    ('jumping-jacks', 'Jumping jacks', 'fitness', 'duration', 'secondes', 'duration-short', 13),
    ('montees-de-genoux', 'Montées de genoux', 'fitness', 'duration', 'secondes', 'duration-short', 14),
    ('box-jumps', 'Box jumps', 'fitness', 'reps', 'repetitions', 'reps-power', 15),
    ('step-ups', 'Step-ups', 'fitness', 'reps', 'repetitions', 'reps-medium', 16),
    ('corde-a-sauter', 'Corde à sauter', 'fitness', 'duration', 'minutes', 'duration-activity', 17),
    ('planche', 'Planche', 'fitness', 'duration', 'secondes', 'duration-plank', 18),
    ('planche-laterale', 'Planche latérale', 'fitness', 'duration', 'secondes', 'duration-short', 19),
    ('chaise', 'Chaise', 'fitness', 'duration', 'secondes', 'duration-short', 20),
    ('hollow-hold', 'Hollow hold', 'fitness', 'duration', 'secondes', 'duration-short', 21),
    ('crunch', 'Crunch', 'fitness', 'reps', 'repetitions', 'reps-core', 22),
    ('sit-ups', 'Sit-ups', 'fitness', 'reps', 'repetitions', 'reps-core', 23),
    ('releves-de-jambes', 'Relevés de jambes', 'fitness', 'reps', 'repetitions', 'reps-core', 24),
    ('russian-twists', 'Russian twists', 'fitness', 'reps', 'repetitions', 'reps-core', 25),
    ('v-ups', 'V-ups', 'fitness', 'reps', 'repetitions', 'reps-core', 26),
    ('pont-fessier', 'Pont fessier', 'fitness', 'reps', 'repetitions', 'reps-medium', 27),
    ('dead-bug', 'Dead bug', 'fitness', 'reps', 'repetitions', 'reps-core', 28),
    ('bird-dog', 'Bird dog', 'fitness', 'reps', 'repetitions', 'reps-core', 29),
    ('superman-hold', 'Superman hold', 'fitness', 'duration', 'secondes', 'duration-short', 30),
    ('tractions', 'Tractions', 'musculation', 'reps', 'repetitions', 'reps-hard', 1),
    ('tractions-supination', 'Tractions supination', 'musculation', 'reps', 'repetitions', 'reps-hard', 2),
    ('developpe-couche', 'Développé couché', 'musculation', 'volume', 'kg', 'volume-compound-heavy', 3),
    ('developpe-couche-halteres', 'Développé couché haltères', 'musculation', 'volume', 'kg', 'volume-upper-medium', 4),
    ('developpe-incline', 'Développé incliné', 'musculation', 'volume', 'kg', 'volume-upper-medium', 5),
    ('developpe-incline-halteres', 'Développé incliné haltères', 'musculation', 'volume', 'kg', 'volume-upper-medium', 6),
    ('ecartes-halteres', 'Écartés haltères', 'musculation', 'volume', 'kg', 'volume-upper-small', 7),
    ('dips', 'Dips', 'musculation', 'reps', 'repetitions', 'reps-hard', 8),
    ('tirage-vertical', 'Tirage vertical', 'musculation', 'volume', 'kg', 'volume-upper-medium', 9),
    ('tirage-horizontal', 'Tirage horizontal', 'musculation', 'volume', 'kg', 'volume-upper-medium', 10),
    ('rowing-barre', 'Rowing barre', 'musculation', 'volume', 'kg', 'volume-compound-heavy', 11),
    ('rowing-haltere', 'Rowing haltère', 'musculation', 'volume', 'kg', 'volume-upper-medium', 12),
    ('rowing-assis', 'Rowing assis', 'musculation', 'volume', 'kg', 'volume-upper-medium', 13),
    ('souleve-de-terre', 'Soulevé de terre', 'musculation', 'volume', 'kg', 'volume-lower-heavy', 14),
    ('developpe-militaire', 'Développé militaire', 'musculation', 'volume', 'kg', 'volume-upper-medium', 15),
    ('developpe-epaules-halteres', 'Développé épaules haltères', 'musculation', 'volume', 'kg', 'volume-upper-small', 16),
    ('elevations-laterales', 'Élévations latérales', 'musculation', 'volume', 'kg', 'volume-upper-small', 17),
    ('oiseau', 'Oiseau', 'musculation', 'volume', 'kg', 'volume-upper-small', 18),
    ('curl-barre', 'Curl barre', 'musculation', 'volume', 'kg', 'volume-upper-small', 19),
    ('curl-halteres', 'Curl haltères', 'musculation', 'volume', 'kg', 'volume-upper-small', 20),
    ('curl-marteau', 'Curl marteau', 'musculation', 'volume', 'kg', 'volume-upper-small', 21),
    ('extension-triceps-poulie', 'Extension triceps poulie', 'musculation', 'volume', 'kg', 'volume-upper-small', 22),
    ('barre-au-front', 'Barre au front', 'musculation', 'volume', 'kg', 'volume-upper-small', 23),
    ('extension-triceps-au-dessus-de-la-tete', 'Extension triceps au-dessus de la tête', 'musculation', 'volume', 'kg', 'volume-upper-small', 24),
    ('squat', 'Squat', 'musculation', 'reps', 'repetitions', 'reps-squat', 25),
    ('front-squat', 'Front squat', 'musculation', 'volume', 'kg', 'volume-lower-heavy', 26),
    ('presse-a-cuisses', 'Presse à cuisses', 'musculation', 'volume', 'kg', 'volume-lower-heavy', 27),
    ('fentes-bulgares', 'Fentes bulgares', 'musculation', 'volume', 'kg', 'volume-upper-medium', 28),
    ('hip-thrust', 'Hip thrust', 'musculation', 'volume', 'kg', 'volume-lower-heavy', 29),
    ('mollets-debout', 'Mollets debout', 'musculation', 'volume', 'kg', 'volume-upper-small', 30),
    ('distance-cap', 'Distance CAP', 'course-a-pied', 'distance', 'km', 'distance-run', 1),
    ('dplus-cap', 'D+ CAP', 'course-a-pied', 'elevation', 'm', 'elevation-run', 2),
    ('duree-cap', 'Durée CAP', 'course-a-pied', 'duration', 'minutes', 'duration-activity', 3),
    ('sorties-cap', 'Sorties CAP', 'course-a-pied', 'count', 'sorties', 'count-sessions', 4),
    ('cap-5km-termines', '5 km terminés', 'course-a-pied', 'count', 'courses', 'count-events', 5),
    ('cap-10km-termines', '10 km terminés', 'course-a-pied', 'count', 'courses', 'count-events', 6),
    ('semi-marathons-termines', 'Semi-marathons terminés', 'course-a-pied', 'count', 'courses', 'count-events', 7),
    ('marathons-termines', 'Marathons terminés', 'course-a-pied', 'count', 'courses', 'count-events', 8),
    ('distance-trail', 'Distance Trail', 'trail', 'distance', 'km', 'distance-trail', 1),
    ('dplus-trail', 'D+ Trail', 'trail', 'elevation', 'm', 'elevation-trail', 2),
    ('duree-trail', 'Durée Trail', 'trail', 'duration', 'minutes', 'duration-activity', 3),
    ('sorties-trail', 'Sorties Trail', 'trail', 'count', 'sorties', 'count-sessions', 4),
    ('trails-20km', 'Trails 20 km+', 'trail', 'count', 'trails', 'count-events', 5),
    ('trails-40km', 'Trails 40 km+', 'trail', 'count', 'trails', 'count-events', 6),
    ('trails-60km', 'Trails 60 km+', 'trail', 'count', 'trails', 'count-events', 7),
    ('trails-80km', 'Trails 80 km+', 'trail', 'count', 'trails', 'count-events', 8),
    ('marche', 'Marche', 'marche', 'distance', 'km', 'distance-walk', 1),
    ('dplus-marche', 'D+ Marche', 'marche', 'elevation', 'm', 'elevation-walk', 2),
    ('duree-marche', 'Durée Marche', 'marche', 'duration', 'minutes', 'duration-activity', 3),
    ('sorties-marche', 'Sorties Marche', 'marche', 'count', 'sorties', 'count-sessions', 4),
    ('pas', 'Pas', 'marche', 'count', 'pas', 'count-steps', 5),
    ('marches-10km', 'Marches 10 km+', 'marche', 'count', 'sorties', 'count-events', 6),
    ('marches-20km', 'Marches 20 km+', 'marche', 'count', 'sorties', 'count-events', 7),
    ('randonnees-30km', 'Randonnées 30 km+', 'marche', 'count', 'sorties', 'count-events', 8),
    ('distance-velo', 'Distance Vélo', 'velo', 'distance', 'km', 'distance-cycle', 1),
    ('dplus-velo', 'D+ Vélo', 'velo', 'elevation', 'm', 'elevation-cycle', 2),
    ('duree-velo', 'Durée Vélo', 'velo', 'duration', 'minutes', 'duration-activity', 3),
    ('sorties-velo', 'Sorties Vélo', 'velo', 'count', 'sorties', 'count-sessions', 4),
    ('sorties-velo-50km', 'Sorties Vélo 50 km+', 'velo', 'count', 'sorties', 'count-events', 5),
    ('sorties-velo-100km', 'Sorties Vélo 100 km+', 'velo', 'count', 'sorties', 'count-events', 6),
    ('distance-vtt', 'Distance VTT', 'vtt', 'distance', 'km', 'distance-trail', 1),
    ('dplus-vtt', 'D+ VTT', 'vtt', 'elevation', 'm', 'elevation-trail', 2),
    ('duree-vtt', 'Durée VTT', 'vtt', 'duration', 'minutes', 'duration-activity', 3),
    ('sorties-vtt', 'Sorties VTT', 'vtt', 'count', 'sorties', 'count-sessions', 4),
    ('distance-natation', 'Distance Natation', 'natation', 'distance', 'km', 'distance-swim', 1),
    ('duree-natation', 'Durée Natation', 'natation', 'duration', 'minutes', 'duration-activity', 2),
    ('seances-natation', 'Séances Natation', 'natation', 'count', 'seances', 'count-sessions', 3),
    ('crawl', 'Crawl', 'natation', 'distance', 'km', 'distance-swim', 4),
    ('brasse', 'Brasse', 'natation', 'distance', 'km', 'distance-swim', 5),
    ('dos', 'Dos', 'natation', 'distance', 'km', 'distance-swim', 6),
    ('papillon', 'Papillon', 'natation', 'distance', 'km', 'distance-swim', 7),
    ('rameur', 'Rameur', 'cardio-indoor', 'distance', 'km', 'distance-outdoor-medium', 1),
    ('air-bike', 'Air bike', 'cardio-indoor', 'duration', 'minutes', 'duration-activity', 2),
    ('course-tapis', 'Course tapis', 'cardio-indoor', 'distance', 'km', 'distance-run', 3),
    ('velo-elliptique', 'Vélo elliptique', 'cardio-indoor', 'duration', 'minutes', 'duration-activity', 4),
    ('ski-erg', 'Ski erg', 'cardio-indoor', 'distance', 'km', 'distance-outdoor-medium', 5),
    ('mobilite-dynamique', 'Mobilité dynamique', 'mobilite-souplesse', 'duration', 'minutes', 'duration-activity', 1),
    ('cercles-epaules', 'Cercles d’épaules', 'mobilite-souplesse', 'duration', 'minutes', 'duration-activity', 2),
    ('rotation-buste', 'Rotation du buste', 'mobilite-souplesse', 'duration', 'minutes', 'duration-activity', 3),
    ('rotation-thoracique', 'Rotation thoracique', 'mobilite-souplesse', 'duration', 'minutes', 'duration-activity', 4),
    ('etirement-ischios', 'Étirement ischios', 'mobilite-souplesse', 'duration', 'minutes', 'duration-activity', 5),
    ('ouverture-hanches', 'Ouverture de hanches', 'mobilite-souplesse', 'duration', 'minutes', 'duration-activity', 6),
    ('respiration-calme', 'Respiration calme', 'mobilite-souplesse', 'duration', 'minutes', 'duration-activity', 7),
    ('respiration-diaphragmatique', 'Respiration diaphragmatique', 'mobilite-souplesse', 'duration', 'minutes', 'duration-activity', 8),
    ('ouverture-thoracique', 'Ouverture thoracique', 'mobilite-souplesse', 'duration', 'minutes', 'duration-activity', 9),
    ('etirement-chaine-posterieure', 'Étirement chaîne postérieure', 'mobilite-souplesse', 'duration', 'minutes', 'duration-activity', 10),
    ('etirements-doux', 'Étirements doux', 'mobilite-souplesse', 'duration', 'minutes', 'duration-activity', 11),
    ('retour-calme-assis', 'Retour calme assis', 'mobilite-souplesse', 'duration', 'minutes', 'duration-activity', 12),
    ('duree-ski-alpin', 'Durée Ski alpin', 'ski-alpin', 'duration', 'minutes', 'duration-activity', 1),
    ('sorties-ski-alpin', 'Sorties Ski alpin', 'ski-alpin', 'count', 'sorties', 'count-sessions', 2),
    ('distance-ski-randonnee', 'Distance Ski de randonnée', 'ski-randonnee', 'distance', 'km', 'distance-trail', 1),
    ('dplus-ski-randonnee', 'D+ Ski de randonnée', 'ski-randonnee', 'elevation', 'm', 'elevation-trail', 2),
    ('duree-ski-randonnee', 'Durée Ski de randonnée', 'ski-randonnee', 'duration', 'minutes', 'duration-activity', 3),
    ('sorties-ski-randonnee', 'Sorties Ski de randonnée', 'ski-randonnee', 'count', 'sorties', 'count-sessions', 4),
    ('sorties-ski-randonnee-1000dplus', 'Sorties Ski de randonnée 1000 m D+', 'ski-randonnee', 'count', 'sorties', 'count-events', 5),
    ('distance-ski-fond', 'Distance Ski de fond', 'ski-de-fond', 'distance', 'km', 'distance-trail', 1),
    ('duree-ski-fond', 'Durée Ski de fond', 'ski-de-fond', 'duration', 'minutes', 'duration-activity', 2),
    ('sorties-ski-fond', 'Sorties Ski de fond', 'ski-de-fond', 'count', 'sorties', 'count-sessions', 3),
    ('distance-raquettes', 'Distance Raquettes', 'raquettes', 'distance', 'km', 'distance-walk', 1),
    ('dplus-raquettes', 'D+ Raquettes', 'raquettes', 'elevation', 'm', 'elevation-walk', 2),
    ('sorties-raquettes', 'Sorties Raquettes', 'raquettes', 'count', 'sorties', 'count-sessions', 3),
    ('duree-escalade', 'Durée Escalade', 'escalade', 'duration', 'minutes', 'duration-activity', 1),
    ('seances-escalade', 'Séances Escalade', 'escalade', 'count', 'seances', 'count-sessions', 2),
    ('voies-realisees', 'Voies réalisées', 'escalade', 'count', 'voies', 'count-sessions', 3),
    ('blocs-realises', 'Blocs réalisés', 'escalade', 'count', 'blocs', 'count-sessions', 4),
    ('duree-via-ferrata', 'Durée Via ferrata', 'via-ferrata', 'duration', 'minutes', 'duration-activity', 1),
    ('sorties-via-ferrata', 'Sorties Via ferrata', 'via-ferrata', 'count', 'sorties', 'count-sessions', 2),
    ('dplus-via-ferrata', 'D+ Via ferrata', 'via-ferrata', 'elevation', 'm', 'elevation-walk', 3),
    ('dplus-alpinisme', 'D+ Alpinisme', 'alpinisme', 'elevation', 'm', 'elevation-trail', 1),
    ('duree-alpinisme', 'Durée Alpinisme', 'alpinisme', 'duration', 'minutes', 'duration-activity', 2),
    ('sorties-alpinisme', 'Sorties Alpinisme', 'alpinisme', 'count', 'sorties', 'count-sessions', 3),
    ('distance-course-orientation', 'Distance Course d’orientation', 'course-orientation', 'distance', 'km', 'distance-run', 1),
    ('duree-course-orientation', 'Durée Course d’orientation', 'course-orientation', 'duration', 'minutes', 'duration-activity', 2),
    ('sorties-course-orientation', 'Sorties Course d’orientation', 'course-orientation', 'count', 'sorties', 'count-sessions', 3),
    ('distance-gravel', 'Distance Gravel', 'gravel', 'distance', 'km', 'distance-cycle', 1),
    ('dplus-gravel', 'D+ Gravel', 'gravel', 'elevation', 'm', 'elevation-cycle', 2),
    ('sorties-gravel', 'Sorties Gravel', 'gravel', 'count', 'sorties', 'count-sessions', 3),
    ('duree-home-trainer', 'Durée Home trainer', 'home-trainer', 'duration', 'minutes', 'duration-activity', 1),
    ('distance-home-trainer', 'Distance Home trainer', 'home-trainer', 'distance', 'km', 'distance-cycle', 2),
    ('seances-home-trainer', 'Séances Home trainer', 'home-trainer', 'count', 'seances', 'count-sessions', 3),
    ('duree-football', 'Durée Football', 'football', 'duration', 'minutes', 'duration-activity', 1),
    ('matchs-football', 'Matchs Football', 'football', 'count', 'matchs', 'count-sessions', 2),
    ('duree-rugby', 'Durée Rugby', 'rugby', 'duration', 'minutes', 'duration-activity', 1),
    ('matchs-rugby', 'Matchs Rugby', 'rugby', 'count', 'matchs', 'count-sessions', 2),
    ('duree-basketball', 'Durée Basketball', 'basketball', 'duration', 'minutes', 'duration-activity', 1),
    ('matchs-basketball', 'Matchs Basketball', 'basketball', 'count', 'matchs', 'count-sessions', 2),
    ('duree-handball', 'Durée Handball', 'handball', 'duration', 'minutes', 'duration-activity', 1),
    ('matchs-handball', 'Matchs Handball', 'handball', 'count', 'matchs', 'count-sessions', 2),
    ('duree-volleyball', 'Durée Volleyball', 'volleyball', 'duration', 'minutes', 'duration-activity', 1),
    ('matchs-volleyball', 'Matchs Volleyball', 'volleyball', 'count', 'matchs', 'count-sessions', 2),
    ('duree-tennis', 'Durée Tennis', 'tennis', 'duration', 'minutes', 'duration-activity', 1),
    ('matchs-tennis', 'Matchs Tennis', 'tennis', 'count', 'matchs', 'count-sessions', 2),
    ('duree-padel', 'Durée Padel', 'padel', 'duration', 'minutes', 'duration-activity', 1),
    ('matchs-padel', 'Matchs Padel', 'padel', 'count', 'matchs', 'count-sessions', 2),
    ('duree-badminton', 'Durée Badminton', 'badminton', 'duration', 'minutes', 'duration-activity', 1),
    ('matchs-badminton', 'Matchs Badminton', 'badminton', 'count', 'matchs', 'count-sessions', 2),
    ('duree-tennis-de-table', 'Durée Tennis de table', 'tennis-de-table', 'duration', 'minutes', 'duration-activity', 1),
    ('matchs-tennis-de-table', 'Matchs Tennis de table', 'tennis-de-table', 'count', 'matchs', 'count-sessions', 2),
    ('duree-boxe', 'Durée Boxe', 'boxe', 'duration', 'minutes', 'duration-activity', 1),
    ('seances-boxe', 'Séances Boxe', 'boxe', 'count', 'seances', 'count-sessions', 2),
    ('duree-sports-de-combat', 'Durée Sports de combat', 'sports-de-combat', 'duration', 'minutes', 'duration-activity', 1),
    ('seances-sports-de-combat', 'Séances Sports de combat', 'sports-de-combat', 'count', 'seances', 'count-sessions', 2),
    ('duree-danse', 'Durée Danse', 'danse', 'duration', 'minutes', 'duration-activity', 1),
    ('seances-danse', 'Séances Danse', 'danse', 'count', 'seances', 'count-sessions', 2),
    ('distance-kayak-canoe', 'Distance Kayak / Canoë', 'kayak-canoe', 'distance', 'km', 'distance-outdoor-medium', 1),
    ('duree-kayak-canoe', 'Durée Kayak / Canoë', 'kayak-canoe', 'duration', 'minutes', 'duration-activity', 2),
    ('sorties-kayak-canoe', 'Sorties Kayak / Canoë', 'kayak-canoe', 'count', 'sorties', 'count-sessions', 3),
    ('distance-aviron', 'Distance Aviron', 'aviron', 'distance', 'km', 'distance-outdoor-medium', 1),
    ('duree-aviron', 'Durée Aviron', 'aviron', 'duration', 'minutes', 'duration-activity', 2),
    ('sorties-aviron', 'Sorties Aviron', 'aviron', 'count', 'sorties', 'count-sessions', 3),
    ('distance-paddle', 'Distance Paddle', 'paddle', 'distance', 'km', 'distance-outdoor-medium', 1),
    ('duree-paddle', 'Durée Paddle', 'paddle', 'duration', 'minutes', 'duration-activity', 2),
    ('sorties-paddle', 'Sorties Paddle', 'paddle', 'count', 'sorties', 'count-sessions', 3),
    ('duree-surf', 'Durée Surf', 'surf', 'duration', 'minutes', 'duration-activity', 1),
    ('sorties-surf', 'Sorties Surf', 'surf', 'count', 'sorties', 'count-sessions', 2),
    ('distance-roller-patinage', 'Distance Roller / Patinage', 'roller-patinage', 'distance', 'km', 'distance-outdoor-medium', 1),
    ('duree-roller-patinage', 'Durée Roller / Patinage', 'roller-patinage', 'duration', 'minutes', 'duration-activity', 2),
    ('sorties-roller-patinage', 'Sorties Roller / Patinage', 'roller-patinage', 'count', 'sorties', 'count-sessions', 3),
    ('distance-triathlon', 'Distance Triathlon', 'triathlon', 'distance', 'km', 'distance-cycle', 1),
    ('duree-triathlon', 'Durée Triathlon', 'triathlon', 'duration', 'minutes', 'duration-activity', 2),
    ('epreuves-triathlon', 'Épreuves Triathlon', 'triathlon', 'count', 'epreuves', 'count-events', 3),
    ('thrusters', 'Thrusters', 'hyrox-cross-training', 'reps', 'repetitions', 'reps-medium', 1),
    ('kettlebell-swings', 'Kettlebell swings', 'hyrox-cross-training', 'reps', 'repetitions', 'reps-medium', 2),
    ('clean-and-press', 'Clean and press', 'hyrox-cross-training', 'reps', 'repetitions', 'reps-medium', 3),
    ('wall-balls', 'Wall balls', 'hyrox-cross-training', 'reps', 'repetitions', 'reps-medium', 4),
    ('seances-hyrox', 'Séances HYROX / Cross-training', 'hyrox-cross-training', 'count', 'seances', 'count-sessions', 5)
),
upsert_masteries as (
  insert into public.masteries (
    slug,
    name,
    category_id,
    measurement_type,
    unit,
    description,
    active,
    sort_order
  )
  select
    ms.slug,
    ms.name,
    mc.id,
    ms.measurement_type,
    ms.unit,
    case ms.measurement_type
      when 'reps' then 'Répétitions cumulées sur ' || ms.name || '.'
      when 'duration' then 'Temps cumulé sur ' || ms.name || '.'
      when 'distance' then 'Distance cumulée sur ' || ms.name || '.'
      when 'elevation' then 'Dénivelé positif cumulé sur ' || ms.name || '.'
      when 'volume' then 'Volume cumulé sur ' || ms.name || ' en kg.'
      when 'count' then 'Occurrences cumulées sur ' || ms.name || '.'
      else 'Progression cumulée sur ' || ms.name || '.'
    end,
    true,
    ms.sort_order
  from mastery_seed ms
  join public.mastery_categories mc
    on mc.slug = ms.category_slug
  on conflict (slug) do update
  set
    name = excluded.name,
    category_id = excluded.category_id,
    measurement_type = excluded.measurement_type,
    unit = excluded.unit,
    description = excluded.description,
    active = true,
    sort_order = excluded.sort_order
  returning id, slug
),
level_family_seed(family, thresholds) as (
  values
    ('reps-easy', array[10,25,50,100,200,350,600,1000,1500,2500,4000,6000,9000,13000,18000,25000,35000,50000,70000,100000]::numeric[]),
    ('reps-medium', array[8,20,40,80,140,230,360,550,800,1200,1700,2400,3300,4500,6000,8000,10500,13500,17000,22000]::numeric[]),
    ('reps-power', array[5,15,30,60,100,160,250,400,650,1000,1500,2200,3200,4500,6500,9000,12000,16000,21000,28000]::numeric[]),
    ('reps-core', array[15,40,80,150,250,400,650,1000,1500,2200,3200,4500,6500,9000,12500,17000,23000,30000,40000,55000]::numeric[]),
    ('reps-hard', array[3,10,20,40,75,125,200,350,550,800,1200,1800,2500,3500,5000,7000,10000,14000,20000,30000]::numeric[]),
    ('reps-squat', array[20,50,100,200,350,600,1000,1500,2500,4000,6000,9000,13000,18000,25000,35000,50000,70000,100000,150000]::numeric[]),
    ('reps-burpees', array[10,25,50,100,175,300,500,800,1250,2000,3000,4500,6500,9000,12000,17000,23000,32000,45000,60000]::numeric[]),
    ('duration-short', array[30,90,180,360,600,900,1500,2400,3600,5400,7200,10800,14400,21600,28800,39600,54000,72000,100000,130000]::numeric[]),
    ('duration-plank', array[60,180,300,600,1200,2100,3600,5400,9000,14400,21600,32400,46800,64800,90000,126000,180000,252000,360000,540000]::numeric[]),
    ('duration-activity', array[30,90,180,360,600,900,1300,1800,2500,3400,4500,6000,7800,9800,12200,15000,18500,22500,27000,32000]::numeric[]),
    ('distance-run', array[1,5,10,25,50,100,175,300,500,750,1000,1500,2000,2750,3500,4500,6000,8000,10000,15000]::numeric[]),
    ('elevation-run', array[50,150,300,600,1000,2000,3500,6000,10000,15000,25000,40000,60000,90000,130000,180000,250000,350000,500000,750000]::numeric[]),
    ('distance-cycle', array[5,15,30,60,100,200,350,600,1000,1500,2000,3000,4000,5500,7500,10000,13000,17000,22000,30000]::numeric[]),
    ('elevation-cycle', array[50,200,500,1000,2000,4000,7000,12000,20000,30000,45000,65000,90000,125000,170000,230000,310000,420000,560000,750000]::numeric[]),
    ('distance-walk', array[1,5,10,25,50,100,200,350,600,1000,1500,2250,3000,4000,5000,6500,8500,11000,15000,20000]::numeric[]),
    ('elevation-walk', array[50,150,300,600,1000,2000,4000,7000,12000,20000,30000,45000,65000,90000,125000,170000,230000,310000,420000,560000]::numeric[]),
    ('distance-trail', array[5,15,30,60,100,160,250,400,600,900,1300,1800,2400,3200,4200,5500,7000,9000,11500,15000]::numeric[]),
    ('elevation-trail', array[100,300,600,1200,2000,3500,6000,10000,15000,22000,32000,45000,65000,90000,125000,170000,230000,310000,420000,560000]::numeric[]),
    ('distance-swim', array[0.5,1,2,4,6,10,15,25,40,60,90,130,180,250,340,450,600,800,1050,1400]::numeric[]),
    ('distance-outdoor-medium', array[2,5,10,20,35,60,100,160,250,400,600,850,1150,1500,1900,2400,3000,3800,4700,6000]::numeric[]),
    ('volume-upper-small', array[150,350,700,1400,2600,4500,7500,12000,18000,26000,37000,52000,72000,98000,130000,170000,220000,280000,360000,450000]::numeric[]),
    ('volume-upper-medium', array[300,700,1500,3000,5500,9000,15000,24000,37000,55000,80000,115000,160000,220000,300000,400000,530000,700000,900000,1200000]::numeric[]),
    ('volume-compound-heavy', array[500,1000,2000,4000,7500,12000,20000,35000,55000,80000,120000,180000,250000,350000,500000,700000,1000000,1400000,2000000,3000000]::numeric[]),
    ('volume-lower-heavy', array[800,2000,4000,8000,15000,25000,40000,65000,100000,150000,220000,320000,450000,620000,850000,1150000,1550000,2050000,2700000,3500000]::numeric[]),
    ('count-sessions', array[1,3,5,10,15,25,40,60,85,120,160,210,270,340,420,520,650,800,1000,1250]::numeric[]),
    ('count-events', array[1,2,3,5,8,12,18,25,35,50,70,95,125,160,210,270,340,420,520,650]::numeric[]),
    ('count-steps', array[2000,5000,10000,20000,35000,50000,75000,100000,150000,200000,300000,400000,550000,700000,900000,1100000,1400000,1700000,2100000,2600000]::numeric[])
),
level_rows as (
  select
    um.id as mastery_id,
    gs.idx as level,
    lfs.thresholds[gs.idx] as threshold
  from upsert_masteries um
  join mastery_seed ms
    on ms.slug = um.slug
  join level_family_seed lfs
    on lfs.family = ms.level_family
  cross join lateral generate_subscripts(lfs.thresholds, 1) as gs(idx)
)
insert into public.mastery_levels (mastery_id, level, threshold, xp_reward)
select
  lr.mastery_id,
  lr.level,
  lr.threshold,
  case when lr.level <= 10 then 5 else 10 end
from level_rows lr
on conflict (mastery_id, level) do update
set
  threshold = excluded.threshold,
  xp_reward = excluded.xp_reward;

with
muscle_seed(mastery_slug, muscle_key, weight) as (
  values
    ('pompes', 'pectoraux', 1),
    ('pompes', 'triceps', 0.6),
    ('pompes', 'epaules', 0.3),
    ('pompes-adaptees', 'pectoraux', 1),
    ('pompes-adaptees', 'triceps', 0.6),
    ('pompes-adaptees', 'epaules', 0.3),
    ('pompes-inclinees', 'pectoraux', 1),
    ('pompes-inclinees', 'triceps', 0.6),
    ('pompes-inclinees', 'epaules', 0.3),
    ('pompes-diamant', 'triceps', 1),
    ('pompes-diamant', 'pectoraux', 0.6),
    ('pompes-diamant', 'epaules', 0.3),
    ('squats-poids-du-corps', 'quadriceps', 1),
    ('squats-poids-du-corps', 'fessiers', 0.6),
    ('squats-poids-du-corps', 'ischios', 0.3),
    ('squats-sautes', 'quadriceps', 1),
    ('squats-sautes', 'fessiers', 0.6),
    ('squats-sautes', 'ischios', 0.3),
    ('fentes-alternees', 'quadriceps', 1),
    ('fentes-alternees', 'fessiers', 0.6),
    ('fentes-alternees', 'ischios', 0.3),
    ('fentes-arriere', 'quadriceps', 1),
    ('fentes-arriere', 'fessiers', 0.6),
    ('fentes-arriere', 'ischios', 0.3),
    ('burpees', 'quadriceps', 0.6),
    ('burpees', 'pectoraux', 0.6),
    ('burpees', 'epaules', 0.3),
    ('burpees', 'abdominaux', 0.3),
    ('burpees-adaptes', 'quadriceps', 0.6),
    ('burpees-adaptes', 'pectoraux', 0.6),
    ('burpees-adaptes', 'epaules', 0.3),
    ('burpees-adaptes', 'abdominaux', 0.3),
    ('mountain-climbers', 'abdominaux', 1),
    ('mountain-climbers', 'epaules', 0.3),
    ('mountain-climbers', 'quadriceps', 0.3),
    ('mountain-climbers-controles', 'abdominaux', 1),
    ('mountain-climbers-controles', 'epaules', 0.3),
    ('mountain-climbers-controles', 'quadriceps', 0.3),
    ('montees-de-genoux', 'quadriceps', 0.6),
    ('montees-de-genoux', 'mollets', 0.3),
    ('montees-de-genoux', 'abdominaux', 0.3),
    ('planche', 'abdominaux', 1),
    ('planche', 'lombaires', 0.6),
    ('planche', 'epaules', 0.3),
    ('planche-laterale', 'abdominaux', 1),
    ('planche-laterale', 'obliques', 0.6),
    ('planche-laterale', 'lombaires', 0.3),
    ('chaise', 'quadriceps', 1),
    ('chaise', 'fessiers', 0.6),
    ('chaise', 'mollets', 0.3),
    ('hollow-hold', 'abdominaux', 1),
    ('hollow-hold', 'obliques', 0.3),
    ('crunch', 'abdominaux', 1),
    ('sit-ups', 'abdominaux', 1),
    ('sit-ups', 'lombaires', 0.3),
    ('releves-de-jambes', 'abdominaux', 1),
    ('russian-twists', 'abdominaux', 1),
    ('russian-twists', 'obliques', 0.6),
    ('v-ups', 'abdominaux', 1),
    ('pont-fessier', 'fessiers', 1),
    ('pont-fessier', 'ischios', 0.6),
    ('dead-bug', 'abdominaux', 1),
    ('dead-bug', 'lombaires', 0.3),
    ('bird-dog', 'lombaires', 1),
    ('bird-dog', 'fessiers', 0.6),
    ('bird-dog', 'abdominaux', 0.3),
    ('superman-hold', 'lombaires', 1),
    ('superman-hold', 'fessiers', 0.6),
    ('tractions', 'grand-dorsal', 1),
    ('tractions', 'biceps', 0.6),
    ('tractions', 'avant-bras', 0.3),
    ('tractions-supination', 'biceps', 1),
    ('tractions-supination', 'grand-dorsal', 0.6),
    ('tractions-supination', 'avant-bras', 0.3),
    ('developpe-couche', 'pectoraux', 1),
    ('developpe-couche', 'triceps', 0.6),
    ('developpe-couche', 'epaules', 0.3),
    ('developpe-couche-halteres', 'pectoraux', 1),
    ('developpe-couche-halteres', 'triceps', 0.6),
    ('developpe-couche-halteres', 'epaules', 0.3),
    ('developpe-incline', 'pectoraux', 1),
    ('developpe-incline', 'epaules', 0.6),
    ('developpe-incline', 'triceps', 0.3),
    ('developpe-incline-halteres', 'pectoraux', 1),
    ('developpe-incline-halteres', 'epaules', 0.6),
    ('developpe-incline-halteres', 'triceps', 0.3),
    ('ecartes-halteres', 'pectoraux', 1),
    ('ecartes-halteres', 'epaules', 0.3),
    ('dips', 'triceps', 1),
    ('dips', 'pectoraux', 0.6),
    ('dips', 'epaules', 0.3),
    ('tirage-vertical', 'grand-dorsal', 1),
    ('tirage-vertical', 'biceps', 0.6),
    ('tirage-vertical', 'avant-bras', 0.3),
    ('tirage-horizontal', 'dos', 1),
    ('tirage-horizontal', 'biceps', 0.6),
    ('tirage-horizontal', 'trapezes', 0.3),
    ('rowing-barre', 'dos', 1),
    ('rowing-barre', 'grand-dorsal', 0.6),
    ('rowing-barre', 'biceps', 0.3),
    ('rowing-haltere', 'dos', 1),
    ('rowing-haltere', 'grand-dorsal', 0.6),
    ('rowing-haltere', 'biceps', 0.3),
    ('rowing-assis', 'dos', 1),
    ('rowing-assis', 'grand-dorsal', 0.6),
    ('rowing-assis', 'biceps', 0.3),
    ('souleve-de-terre', 'ischios', 1),
    ('souleve-de-terre', 'fessiers', 1),
    ('souleve-de-terre', 'lombaires', 0.6),
    ('souleve-de-terre', 'trapezes', 0.3),
    ('developpe-militaire', 'epaules', 1),
    ('developpe-militaire', 'triceps', 0.6),
    ('developpe-epaules-halteres', 'epaules', 1),
    ('developpe-epaules-halteres', 'triceps', 0.3),
    ('elevations-laterales', 'epaules', 1),
    ('oiseau', 'epaules', 1),
    ('oiseau', 'trapezes', 0.3),
    ('curl-barre', 'biceps', 1),
    ('curl-barre', 'avant-bras', 0.3),
    ('curl-halteres', 'biceps', 1),
    ('curl-halteres', 'avant-bras', 0.3),
    ('curl-marteau', 'avant-bras', 1),
    ('curl-marteau', 'biceps', 0.6),
    ('extension-triceps-poulie', 'triceps', 1),
    ('barre-au-front', 'triceps', 1),
    ('extension-triceps-au-dessus-de-la-tete', 'triceps', 1),
    ('squat', 'quadriceps', 1),
    ('squat', 'fessiers', 1),
    ('squat', 'ischios', 0.6),
    ('front-squat', 'quadriceps', 1),
    ('front-squat', 'fessiers', 0.6),
    ('front-squat', 'abdominaux', 0.3),
    ('presse-a-cuisses', 'quadriceps', 1),
    ('presse-a-cuisses', 'fessiers', 1),
    ('presse-a-cuisses', 'ischios', 0.6),
    ('fentes-bulgares', 'quadriceps', 1),
    ('fentes-bulgares', 'fessiers', 1),
    ('fentes-bulgares', 'ischios', 0.6),
    ('hip-thrust', 'fessiers', 1),
    ('hip-thrust', 'ischios', 0.6),
    ('hip-thrust', 'lombaires', 0.3),
    ('mollets-debout', 'mollets', 1)
)
insert into public.mastery_muscles (mastery_id, muscle_key, weight)
select
  m.id,
  ms.muscle_key,
  ms.weight
from muscle_seed ms
join public.masteries m
  on m.slug = ms.mastery_slug
on conflict (mastery_id, muscle_key) do update
set
  weight = excluded.weight;

with
link_seed(source_type, exercise_key, exercise_name, mastery_slug) as (
  values
    ('exercise_library', 'developpe-couche', 'Developpe couche', 'developpe-couche'),
    ('exercise_library', 'developpe-incline', 'Developpe incline', 'developpe-incline'),
    ('exercise_library', 'pompes', 'Pompes', 'pompes'),
    ('exercise_library', 'dips', 'Dips', 'dips'),
    ('exercise_library', 'tirage-vertical', 'Tirage vertical', 'tirage-vertical'),
    ('exercise_library', 'rowing-barre', 'Rowing barre', 'rowing-barre'),
    ('exercise_library', 'rowing-haltere', 'Rowing haltere', 'rowing-haltere'),
    ('exercise_library', 'souleve-de-terre', 'Souleve de terre', 'souleve-de-terre'),
    ('exercise_library', 'squat', 'Squat', 'squat'),
    ('exercise_library', 'presse-inclinee', 'Presse inclinee', 'presse-a-cuisses'),
    ('exercise_library', 'fentes-bulgares', 'Fentes bulgares', 'fentes-bulgares'),
    ('exercise_library', 'mollets-debout', 'Mollets debout', 'mollets-debout'),
    ('exercise_library', 'developpe-militaire', 'Developpe militaire', 'developpe-militaire'),
    ('exercise_library', 'elevations-laterales', 'Elevations laterales', 'elevations-laterales'),
    ('exercise_library', 'oiseau', 'Oiseau', 'oiseau'),
    ('exercise_library', 'curl-barre', 'Curl barre', 'curl-barre'),
    ('exercise_library', 'curl-halteres', 'Curl halteres', 'curl-halteres'),
    ('exercise_library', 'extension-triceps-poulie', 'Extension triceps poulie', 'extension-triceps-poulie'),
    ('exercise_library', 'barre-au-front', 'Barre au front', 'barre-au-front'),
    ('exercise_library', 'gainage', 'Gainage', 'planche'),
    ('exercise_library', 'crunch', 'Crunch', 'crunch'),
    ('exercise_library', 'releve-de-jambes', 'Releve de jambes', 'releves-de-jambes'),
    ('exercise_library', 'burpees', 'Burpees', 'burpees'),
    ('exercise_library', 'rameur', 'Rameur', 'rameur'),
    ('exercise_library', 'air-bike', 'Air bike', 'air-bike'),
    ('exercise_library', 'course-tapis', 'Course tapis', 'course-tapis'),
    ('exercise_library', 'thrusters', 'Thrusters', 'thrusters'),
    ('exercise_library', 'kettlebell-swing', 'Kettlebell swing', 'kettlebell-swings'),
    ('exercise_library', 'clean-and-press', 'Clean and press', 'clean-and-press'),
    ('exercise_library', 'mountain-climbers', 'Mountain climbers', 'mountain-climbers'),
    ('training_block', 'air-bike', 'Air bike', 'air-bike'),
    ('training_block', 'barre-au-front', 'Barre au front', 'barre-au-front'),
    ('training_block', 'bird-dog', 'Bird dog', 'bird-dog'),
    ('training_block', 'burpees', 'Burpees', 'burpees'),
    ('training_block', 'burpees-adaptes', 'Burpees adaptés', 'burpees-adaptes'),
    ('training_block', 'cercles-epaules', 'Cercles d’épaules', 'cercles-epaules'),
    ('training_block', 'chaise-contre-un-mur', 'Chaise contre un mur', 'chaise'),
    ('training_block', 'clean-and-press', 'Clean and press', 'clean-and-press'),
    ('training_block', 'course-tapis', 'Course tapis', 'course-tapis'),
    ('training_block', 'crunch', 'Crunch', 'crunch'),
    ('training_block', 'crunchs', 'Crunchs', 'crunch'),
    ('training_block', 'curl-barre', 'Curl barre', 'curl-barre'),
    ('training_block', 'curl-halteres', 'Curl halteres', 'curl-halteres'),
    ('training_block', 'dead-bug', 'Dead bug', 'dead-bug'),
    ('training_block', 'developpe-couche', 'Developpe couche', 'developpe-couche'),
    ('training_block', 'developpe-halteres-leger', 'Developpe halteres leger', 'developpe-couche-halteres'),
    ('training_block', 'developpe-incline', 'Developpe incline', 'developpe-incline'),
    ('training_block', 'developpe-militaire', 'Developpe militaire', 'developpe-militaire'),
    ('training_block', 'dips', 'Dips', 'dips'),
    ('training_block', 'developpe-halteres', 'Développé haltères', 'developpe-couche-halteres'),
    ('training_block', 'elevations-laterales', 'Elevations laterales', 'elevations-laterales'),
    ('training_block', 'etirement-chaine-posterieure', 'Etirement chaine posterieure', 'etirement-chaine-posterieure'),
    ('training_block', 'extension-triceps-poulie', 'Extension triceps poulie', 'extension-triceps-poulie'),
    ('training_block', 'fentes-alternees', 'Fentes alternées', 'fentes-alternees'),
    ('training_block', 'fentes-arriere', 'Fentes arriere', 'fentes-arriere'),
    ('training_block', 'fentes-bulgares', 'Fentes bulgares', 'fentes-bulgares'),
    ('training_block', 'gainage', 'Gainage', 'planche'),
    ('training_block', 'gainage-cote-droit', 'Gainage côté droit', 'planche-laterale'),
    ('training_block', 'gainage-cote-gauche', 'Gainage côté gauche', 'planche-laterale'),
    ('training_block', 'gainage-face', 'Gainage face', 'planche'),
    ('training_block', 'gainage-frontal', 'Gainage frontal', 'planche'),
    ('training_block', 'hip-thrust', 'Hip thrust', 'hip-thrust'),
    ('training_block', 'jumping-jacks', 'Jumping Jacks', 'jumping-jacks'),
    ('training_block', 'jumping-jacks', 'Jumping jacks', 'jumping-jacks'),
    ('training_block', 'kettlebell-swing', 'Kettlebell swing', 'kettlebell-swings'),
    ('training_block', 'mobilite-dynamique', 'Mobilite dynamique', 'mobilite-dynamique'),
    ('training_block', 'mobilite-hanches', 'Mobilite hanches', 'ouverture-hanches'),
    ('training_block', 'mobilite-hanches', 'Mobilité hanches', 'ouverture-hanches'),
    ('training_block', 'mollets-debout', 'Mollets debout', 'mollets-debout'),
    ('training_block', 'montees-de-genoux', 'Montées de genoux', 'montees-de-genoux'),
    ('training_block', 'mountain-climbers', 'Mountain climbers', 'mountain-climbers'),
    ('training_block', 'mountain-climbers-controles', 'Mountain climbers controles', 'mountain-climbers-controles'),
    ('training_block', 'mountain-climbers-controles', 'Mountain climbers contrôlés', 'mountain-climbers-controles'),
    ('training_block', 'oiseau', 'Oiseau', 'oiseau'),
    ('training_block', 'ouverture-de-hanches', 'Ouverture de hanches', 'ouverture-hanches'),
    ('training_block', 'ouverture-thoracique', 'Ouverture thoracique', 'ouverture-thoracique'),
    ('training_block', 'planche', 'Planche', 'planche'),
    ('training_block', 'pompes', 'Pompes', 'pompes'),
    ('training_block', 'pompes-adaptees', 'Pompes adaptees', 'pompes-adaptees'),
    ('training_block', 'pompes-adaptees', 'Pompes adaptées', 'pompes-adaptees'),
    ('training_block', 'pont-fessier', 'Pont fessier', 'pont-fessier'),
    ('training_block', 'presse', 'Presse', 'presse-a-cuisses'),
    ('training_block', 'presse-a-cuisses', 'Presse a cuisses', 'presse-a-cuisses'),
    ('training_block', 'presse-inclinee', 'Presse inclinee', 'presse-a-cuisses'),
    ('training_block', 'rameur', 'Rameur', 'rameur'),
    ('training_block', 'releve-de-jambes', 'Releve de jambes', 'releves-de-jambes'),
    ('training_block', 'releves-de-jambes', 'Relevés de jambes', 'releves-de-jambes'),
    ('training_block', 'respiration-calme', 'Respiration calme', 'respiration-calme'),
    ('training_block', 'respiration-diaphragmatique', 'Respiration diaphragmatique', 'respiration-diaphragmatique'),
    ('training_block', 'retour-calme-assis', 'Retour calme assis', 'retour-calme-assis'),
    ('training_block', 'rotation-du-buste', 'Rotation du buste', 'rotation-buste'),
    ('training_block', 'rotation-thoracique', 'Rotation thoracique', 'rotation-thoracique'),
    ('training_block', 'rowing', 'Rowing', 'rowing-assis'),
    ('training_block', 'rowing-assis', 'Rowing assis', 'rowing-assis'),
    ('training_block', 'rowing-barre', 'Rowing barre', 'rowing-barre'),
    ('training_block', 'rowing-haltere', 'Rowing haltere', 'rowing-haltere'),
    ('training_block', 'side-plank', 'Side plank', 'planche-laterale'),
    ('training_block', 'souleve-de-terre', 'Souleve de terre', 'souleve-de-terre'),
    ('training_block', 'squat', 'Squat', 'squat'),
    ('training_block', 'squat-goblet', 'Squat goblet', 'squat'),
    ('training_block', 'squats', 'Squats', 'squats-poids-du-corps'),
    ('training_block', 'squats-sautes', 'Squats sautés', 'squats-sautes'),
    ('training_block', 'superman-hold', 'Superman hold', 'superman-hold'),
    ('training_block', 'thrusters', 'Thrusters', 'thrusters'),
    ('training_block', 'tirage-vertical', 'Tirage vertical', 'tirage-vertical'),
    ('training_block', 'etirement-ischios', 'Étirement ischios', 'etirement-ischios'),
    ('training_block', 'etirements-doux', 'Étirements doux', 'etirements-doux')
)
insert into public.mastery_exercise_links (
  mastery_id,
  exercise_key,
  exercise_name,
  source_type
)
select
  m.id,
  ls.exercise_key,
  ls.exercise_name,
  ls.source_type
from link_seed ls
join public.masteries m
  on m.slug = ls.mastery_slug
on conflict (source_type, exercise_name) do update
set
  mastery_id = excluded.mastery_id,
  exercise_key = excluded.exercise_key;

notify pgrst, 'reload schema';

commit;
